name: Despliegue automatico a servidor Firebase Remo
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: portafolio
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env  
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          VITE_APIKEY: ${{ secrets.VITE_APIKEY }}
          VITE_AUTHDOMAIN: ${{ secrets.VITE_AUTHDOMAIN }}
          VITE_DATABASEURL: ${{ secrets.VITE_DATABASEURL }}
          VITE_PROJECTID: ${{ secrets.VITE_PROJECTID }}
          VITE_STORAGEBUCKET: ${{ secrets.VITE_STORAGEBUCKET }}
          VITE_MESSAGINGSENDERID: ${{ secrets.VITE_MESSAGINGSENDERID }}
          VITE_APPID: ${{ secrets.VITE_APPID }}
          VITE_MEASUREMENTID: ${{ secrets.VITE_MEASUREMENTID }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: portafolio
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          


